import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

interface RouteLocation {
  plateNo: string;
  routeId: string;
  stationId: string;
  stationSeq: number;
  remainSeatCnt: number;
}
interface RoutePassingStation {
  centerYn: 'Y' | 'N';
  districtCd: string;
  mobileNo: string;
  regionName: string;
  stationId: string;
  stationName: string;
  x: string;
  y: string;
  stationSeq: number;
  turnYn: 'Y' | 'N';
}

export interface RouteMapInfo {
  routeInfo: {
    companyId: string;
    companyName: string;
    companyTel: string;
    districtCd: string;
    downFirstTime: string;
    downLastTime: string;
    endMobileNo: string;
    endStationId: string;
    endStationName: string;
    peekAlloc: number;
    regionName: string;
    routeId: string;
    routeName: string;
    routeTypeCd: string;
    routeTypeName: string;
    startMobileNo: string;
    startStationId: string;
    startStationName: string;
    upFirstTime: string;
    upLastTime: string;
    nPeekAlloc: number;
  };
  routeLocations: RouteLocation[];
  routePassingStations: RoutePassingStation[];
}

type FetchRouteMap = (routeId: string) => Promise<RouteMapInfo>;

const fetchRouteMap: FetchRouteMap = async (routeId: string) => {
  try {
    // return {
    //   routeInfo: {
    //     companyId: '4100600',
    //     companyName: '경남여객',
    //     companyTel: '031-321-3721',
    //     districtCd: '2',
    //     downFirstTime: '06:30',
    //     downLastTime: '00:00',
    //     endMobileNo: '90234',
    //     endStationId: '121000944',
    //     endStationName: '신논현역.주류성빌딩',
    //     peekAlloc: '12',
    //     regionName: '서울,용인',
    //     routeId: '228000176',
    //     routeName: '5001',
    //     routeTypeCd: '11',
    //     routeTypeName: '직행좌석형시내버스',
    //     startMobileNo: '47632',
    //     startStationId: '228000191',
    //     startStationName: '명지대',
    //     upFirstTime: '05:30',
    //     upLastTime: '23:00',
    //     nPeekAlloc: '15',
    //   },
    //   routeLocations: [
    //     {
    //       plateNo: '경기78아1126',
    //       remainSeatCnt: 47,
    //       routeId: '228000176',
    //       stationId: '228000445',
    //       stationSeq: 80,
    //     },
    //     {
    //       plateNo: '경기78아1269',
    //       remainSeatCnt: 23,
    //       routeId: '228000176',
    //       stationId: '277104178',
    //       stationSeq: 53,
    //     },
    //     {
    //       plateNo: '경기78아1137',
    //       remainSeatCnt: 41,
    //       routeId: '228000176',
    //       stationId: '228000690',
    //       stationSeq: 70,
    //     },
    //     {
    //       plateNo: '경기78아1205',
    //       remainSeatCnt: 29,
    //       routeId: '228000176',
    //       stationId: '277102911',
    //       stationSeq: 44,
    //     },
    //     {
    //       plateNo: '경기78아1145',
    //       remainSeatCnt: 48,
    //       routeId: '228000176',
    //       stationId: '228000449',
    //       stationSeq: 10,
    //     },
    //     {
    //       plateNo: '경기78아1210',
    //       remainSeatCnt: 45,
    //       routeId: '228000176',
    //       stationId: '228000686',
    //       stationSeq: 25,
    //     },
    //     {
    //       plateNo: '경기78아1266',
    //       remainSeatCnt: 43,
    //       routeId: '228000176',
    //       stationId: '277103361',
    //       stationSeq: 33,
    //     },
    //     {
    //       plateNo: '경기78아1108',
    //       remainSeatCnt: 25,
    //       routeId: '228000176',
    //       stationId: '121000001',
    //       stationSeq: 50,
    //     },
    //     {
    //       plateNo: '경기78아1291',
    //       remainSeatCnt: 41,
    //       routeId: '228000176',
    //       stationId: '277103765',
    //       stationSeq: 42,
    //     },
    //     {
    //       plateNo: '경기78아1204',
    //       remainSeatCnt: 15,
    //       routeId: '228000176',
    //       stationId: '277103360',
    //       stationSeq: 59,
    //     },
    //     {
    //       plateNo: '경기78아1133',
    //       remainSeatCnt: 23,
    //       routeId: '228000176',
    //       stationId: '228000696',
    //       stationSeq: 63,
    //     },
    //     {
    //       plateNo: '경기75아6094',
    //       remainSeatCnt: 35,
    //       routeId: '228000176',
    //       stationId: '228000779',
    //       stationSeq: 74,
    //     },
    //   ],
    //   routePassingStations: [
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47632',
    //       regionName: '용인',
    //       stationId: '228000191',
    //       stationName: '명지대',
    //       x: '127.1884667',
    //       y: '37.22425',
    //       stationSeq: 1,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47945',
    //       regionName: '용인',
    //       stationId: '228002958',
    //       stationName: '명지대앞',
    //       x: '127.1883',
    //       y: '37.2257333',
    //       stationSeq: 2,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29407',
    //       regionName: '용인',
    //       stationId: '228000190',
    //       stationName: '동진마을',
    //       x: '127.1929167',
    //       y: '37.2263833',
    //       stationSeq: 3,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29850',
    //       regionName: '용인',
    //       stationId: '228000189',
    //       stationName: '교수마을',
    //       x: '127.1978667',
    //       y: '37.2258167',
    //       stationSeq: 4,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29423',
    //       regionName: '용인',
    //       stationId: '228000188',
    //       stationName: '보보스타운',
    //       x: '127.2039333',
    //       y: '37.2269667',
    //       stationSeq: 5,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29431',
    //       regionName: '용인',
    //       stationId: '228000187',
    //       stationName: '남동구미마을',
    //       x: '127.2090667',
    //       y: '37.2271333',
    //       stationSeq: 6,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47015',
    //       regionName: '용인',
    //       stationId: '228000199',
    //       stationName: '태성중고등학교.현대아파트',
    //       x: '127.21075',
    //       y: '37.22945',
    //       stationSeq: 7,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47592',
    //       regionName: '용인',
    //       stationId: '228000198',
    //       stationName: '현대아파트',
    //       x: '127.20985',
    //       y: '37.2312667',
    //       stationSeq: 8,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29434',
    //       regionName: '용인',
    //       stationId: '228001320',
    //       stationName: '용인터미널',
    //       x: '127.20925',
    //       y: '37.2336667',
    //       stationSeq: 9,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29428',
    //       regionName: '용인',
    //       stationId: '228000449',
    //       stationName: '용인시장.시장약국',
    //       x: '127.2066833',
    //       y: '37.2356',
    //       stationSeq: 10,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29419',
    //       regionName: '용인',
    //       stationId: '228000448',
    //       stationName: '처인구청.용인헌혈의집',
    //       x: '127.2028833',
    //       y: '37.235',
    //       stationSeq: 11,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29413',
    //       regionName: '용인',
    //       stationId: '228000447',
    //       stationName: '중앙지구대.로하스용인병원',
    //       x: '127.19855',
    //       y: '37.2349167',
    //       stationSeq: 12,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29409',
    //       regionName: '용인',
    //       stationId: '228000749',
    //       stationName: '역북초.벽산블루밍.삼환나우빌',
    //       x: '127.19335',
    //       y: '37.2354',
    //       stationSeq: 13,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29405',
    //       regionName: '용인',
    //       stationId: '228000748',
    //       stationName: '명지대입구',
    //       x: '127.1899',
    //       y: '37.2361333',
    //       stationSeq: 14,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29401',
    //       regionName: '용인',
    //       stationId: '228000747',
    //       stationName: '동원로얄듀크.용인등기소',
    //       x: '127.1858167',
    //       y: '37.2369833',
    //       stationSeq: 15,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29801',
    //       regionName: '용인',
    //       stationId: '228000746',
    //       stationName: '역말마을',
    //       x: '127.1821',
    //       y: '37.2377167',
    //       stationSeq: 16,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29399',
    //       regionName: '용인',
    //       stationId: '228000745',
    //       stationName: '시청.용인대역',
    //       x: '127.1799167',
    //       y: '37.2382',
    //       stationSeq: 17,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29392',
    //       regionName: '용인',
    //       stationId: '228000744',
    //       stationName: '진우아파트',
    //       x: '127.1732833',
    //       y: '37.2398833',
    //       stationSeq: 18,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29852',
    //       regionName: '용인',
    //       stationId: '228000743',
    //       stationName: '삼가동.궁촌',
    //       x: '127.1713833',
    //       y: '37.2407167',
    //       stationSeq: 19,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29387',
    //       regionName: '용인',
    //       stationId: '228000742',
    //       stationName: '삼가역.두산위브',
    //       x: '127.16805',
    //       y: '37.2423667',
    //       stationSeq: 20,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29365',
    //       regionName: '용인',
    //       stationId: '228000741',
    //       stationName: '효자고개',
    //       x: '127.1543167',
    //       y: '37.2514',
    //       stationSeq: 21,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29353',
    //       regionName: '용인',
    //       stationId: '228000689',
    //       stationName: '인정프린스.흥국생명연수원',
    //       x: '127.1437333',
    //       y: '37.2560333',
    //       stationSeq: 22,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29346',
    //       regionName: '용인',
    //       stationId: '228000688',
    //       stationName: '수원동.쌍용아파트',
    //       x: '127.1425667',
    //       y: '37.2588167',
    //       stationSeq: 23,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29344',
    //       regionName: '용인',
    //       stationId: '228000687',
    //       stationName: '상지석.대우.진흥아파트',
    //       x: '127.1408833',
    //       y: '37.26145',
    //       stationSeq: 24,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29336',
    //       regionName: '용인',
    //       stationId: '228000686',
    //       stationName: '고인돌.하나로마트.현대출고장',
    //       x: '127.1365667',
    //       y: '37.2668',
    //       stationSeq: 25,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29324',
    //       regionName: '용인',
    //       stationId: '228000685',
    //       stationName: '어정삼거리.강남마을',
    //       x: '127.1298',
    //       y: '37.2687167',
    //       stationSeq: 26,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29307',
    //       regionName: '용인',
    //       stationId: '228000684',
    //       stationName: '강남대역.강남대입구',
    //       x: '127.1255',
    //       y: '37.2712667',
    //       stationSeq: 27,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29278',
    //       regionName: '용인',
    //       stationId: '228000683',
    //       stationName: '수원컨트리클럽',
    //       x: '127.1194333',
    //       y: '37.2759833',
    //       stationSeq: 28,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29262',
    //       regionName: '용인',
    //       stationId: '228000682',
    //       stationName: '기흥역',
    //       x: '127.1145833',
    //       y: '37.2759833',
    //       stationSeq: 29,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29208',
    //       regionName: '용인',
    //       stationId: '228000681',
    //       stationName: '롯데캐슬스카이.이안두드림.백남준아트센터',
    //       x: '127.1087667',
    //       y: '37.2719',
    //       stationSeq: 30,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29145',
    //       regionName: '용인',
    //       stationId: '228000680',
    //       stationName: '상미마을.신갈오거리.롯데캐슬레이시티',
    //       x: '127.1037167',
    //       y: '37.2711667',
    //       stationSeq: 31,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103364',
    //       stationName: '수원신갈TG(경유)',
    //       x: '127.1017167',
    //       y: '37.26785',
    //       stationSeq: 32,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103361',
    //       stationName: '신갈JC(경유)',
    //       x: '127.1038667',
    //       y: '37.2896667',
    //       stationSeq: 33,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103443',
    //       stationName: '죽전(경유)',
    //       x: '127.1038167',
    //       y: '37.3266333',
    //       stationSeq: 34,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103386',
    //       stationName: '서울TG(경유)',
    //       x: '127.1043333',
    //       y: '37.3649667',
    //       stationSeq: 35,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103151',
    //       stationName: '판교IC(경유)',
    //       x: '127.1006167',
    //       y: '37.3986333',
    //       stationSeq: 36,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103679',
    //       stationName: '금토JC(경유)',
    //       x: '127.0853167',
    //       y: '37.4152833',
    //       stationSeq: 37,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103441',
    //       stationName: '서울진입(경유)',
    //       x: '127.0665833',
    //       y: '37.43385',
    //       stationSeq: 38,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277104177',
    //       stationName: '청계산입구역(경유)',
    //       x: '127.0542',
    //       y: '37.4483667',
    //       stationSeq: 39,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103388',
    //       stationName: '양재IC(경유)',
    //       x: '127.04045',
    //       y: '37.4632833',
    //       stationSeq: 40,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103390',
    //       stationName: '서초IC(경유)',
    //       x: '127.0263333',
    //       y: '37.4831333',
    //       stationSeq: 41,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103765',
    //       stationName: '반포IC출입(경유)',
    //       x: '127.0193167',
    //       y: '37.502',
    //       stationSeq: 42,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 90234',
    //       regionName: '서울',
    //       stationId: '121000944',
    //       stationName: '신논현역.주류성빌딩',
    //       x: '127.0258',
    //       y: '37.5011167',
    //       stationSeq: 43,
    //       turnYn: 'Y',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277102911',
    //       stationName: '강남역10번출구(경유)',
    //       x: '127.0269833',
    //       y: '37.4986167',
    //       stationSeq: 44,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'Y',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000009',
    //       stationName: '신분당선강남역(중)',
    //       x: '127.02835',
    //       y: '37.49615',
    //       stationSeq: 45,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277101612',
    //       stationName: '우성아파트앞사거리(경유)',
    //       x: '127.0295333',
    //       y: '37.49335',
    //       stationSeq: 46,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'Y',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000007',
    //       stationName: '래미안아파트.파이낸셜뉴스(중)',
    //       x: '127.0305',
    //       y: '37.4917833',
    //       stationSeq: 47,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'Y',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000005',
    //       stationName: '뱅뱅사거리(중)',
    //       x: '127.0324667',
    //       y: '37.4876833',
    //       stationSeq: 48,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'Y',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000003',
    //       stationName: '양재역.서초문화예술회관(중)',
    //       x: '127.0358833',
    //       y: '37.4825667',
    //       stationSeq: 49,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'Y',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000001',
    //       stationName: '교육개발원입구(중)',
    //       x: '127.0385167',
    //       y: '37.4784667',
    //       stationSeq: 50,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '121000220',
    //       stationName: '시민의숲.양재꽃시장',
    //       x: '127.0383833',
    //       y: '37.4708',
    //       stationSeq: 51,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103387',
    //       stationName: '양재IC(경유)',
    //       x: '127.0394333',
    //       y: '37.46365',
    //       stationSeq: 52,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277104178',
    //       stationName: '청계산입구역(경유)',
    //       x: '127.0538333',
    //       y: '37.4481833',
    //       stationSeq: 53,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '서울',
    //       stationId: '277103440',
    //       stationName: '성남진입(경유)',
    //       x: '127.0661833',
    //       y: '37.43355',
    //       stationSeq: 54,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103678',
    //       stationName: '금토JC(경유)',
    //       x: '127.08445',
    //       y: '37.4155',
    //       stationSeq: 55,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103150',
    //       stationName: '판교IC(경유)',
    //       x: '127.10005',
    //       y: '37.3988333',
    //       stationSeq: 56,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '성남',
    //       stationId: '277103385',
    //       stationName: '서울TG(경유)',
    //       x: '127.1026',
    //       y: '37.36535',
    //       stationSeq: 57,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103442',
    //       stationName: '죽전(경유)',
    //       x: '127.10315',
    //       y: '37.3266',
    //       stationSeq: 58,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103360',
    //       stationName: '신갈JC(경유)',
    //       x: '127.10345',
    //       y: '37.2904333',
    //       stationSeq: 59,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       regionName: '용인',
    //       stationId: '277103365',
    //       stationName: '수원신갈TG(경유)',
    //       x: '127.10215',
    //       y: '37.2682',
    //       stationSeq: 60,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29148',
    //       regionName: '용인',
    //       stationId: '228000698',
    //       stationName: '상미마을.신갈오거리.롯데캐슬레이시티',
    //       x: '127.1030333',
    //       y: '37.27065',
    //       stationSeq: 61,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29224',
    //       regionName: '용인',
    //       stationId: '228000697',
    //       stationName: '롯데캐슬스카이.이안두드림.백남준아트센터',
    //       x: '127.1088833',
    //       y: '37.2716333',
    //       stationSeq: 62,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29269',
    //       regionName: '용인',
    //       stationId: '228000696',
    //       stationName: '기흥역',
    //       x: '127.1168167',
    //       y: '37.276',
    //       stationSeq: 63,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29281',
    //       regionName: '용인',
    //       stationId: '228000695',
    //       stationName: '수원컨트리클럽',
    //       x: '127.1201',
    //       y: '37.2753',
    //       stationSeq: 64,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29306',
    //       regionName: '용인',
    //       stationId: '228000694',
    //       stationName: '강남대역.강남대입구',
    //       x: '127.1256167',
    //       y: '37.2706833',
    //       stationSeq: 65,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29327',
    //       regionName: '용인',
    //       stationId: '228000693',
    //       stationName: '어정삼거리.강남마을',
    //       x: '127.1314333',
    //       y: '37.2681333',
    //       stationSeq: 66,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29335',
    //       regionName: '용인',
    //       stationId: '228001147',
    //       stationName: '고인돌.하나로마트.현대출고장',
    //       x: '127.1356667',
    //       y: '37.26705',
    //       stationSeq: 67,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29343',
    //       regionName: '용인',
    //       stationId: '228000692',
    //       stationName: '상지석.대우.진흥아파트',
    //       x: '127.1401833',
    //       y: '37.2619167',
    //       stationSeq: 68,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29347',
    //       regionName: '용인',
    //       stationId: '228000691',
    //       stationName: '수원동.쌍용아파트',
    //       x: '127.1423667',
    //       y: '37.2587833',
    //       stationSeq: 69,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29354',
    //       regionName: '용인',
    //       stationId: '228000690',
    //       stationName: '인정프린스.흥국생명연수원',
    //       x: '127.1435833',
    //       y: '37.2558667',
    //       stationSeq: 70,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29367',
    //       regionName: '용인',
    //       stationId: '228000782',
    //       stationName: '효자고개',
    //       x: '127.15435',
    //       y: '37.2510833',
    //       stationSeq: 71,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47332',
    //       regionName: '용인',
    //       stationId: '228000781',
    //       stationName: '삼가역.두산위브',
    //       x: '127.16955',
    //       y: '37.2411333',
    //       stationSeq: 72,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29393',
    //       regionName: '용인',
    //       stationId: '228000780',
    //       stationName: '진우아파트',
    //       x: '127.1732667',
    //       y: '37.2395',
    //       stationSeq: 73,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29398',
    //       regionName: '용인',
    //       stationId: '228000779',
    //       stationName: '시청.용인대역',
    //       x: '127.1784667',
    //       y: '37.2380333',
    //       stationSeq: 74,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29400',
    //       regionName: '용인',
    //       stationId: '228000778',
    //       stationName: '역말마을',
    //       x: '127.1822667',
    //       y: '37.23745',
    //       stationSeq: 75,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29402',
    //       regionName: '용인',
    //       stationId: '228000777',
    //       stationName: '동원로얄듀크.용인등기소',
    //       x: '127.1861333',
    //       y: '37.2366167',
    //       stationSeq: 76,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29406',
    //       regionName: '용인',
    //       stationId: '228000776',
    //       stationName: '명지대입구',
    //       x: '127.19',
    //       y: '37.2358',
    //       stationSeq: 77,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29408',
    //       regionName: '용인',
    //       stationId: '228000775',
    //       stationName: '역북초.벽산블루밍.삼환나우빌',
    //       x: '127.1932833',
    //       y: '37.2351',
    //       stationSeq: 78,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29412',
    //       regionName: '용인',
    //       stationId: '228000446',
    //       stationName: '중앙지구대',
    //       x: '127.1988167',
    //       y: '37.23475',
    //       stationSeq: 79,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29420',
    //       regionName: '용인',
    //       stationId: '228000445',
    //       stationName: '처인구청.용인헌혈의집',
    //       x: '127.2035833',
    //       y: '37.23485',
    //       stationSeq: 80,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29425',
    //       regionName: '용인',
    //       stationId: '228000444',
    //       stationName: '용인시장.시장약국',
    //       x: '127.2066833',
    //       y: '37.2354333',
    //       stationSeq: 81,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47633',
    //       regionName: '용인',
    //       stationId: '228001414',
    //       stationName: '용인터미널',
    //       x: '127.2090833',
    //       y: '37.2326167',
    //       stationSeq: 82,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29440',
    //       regionName: '용인',
    //       stationId: '228000236',
    //       stationName: '태성고교',
    //       x: '127.2104333',
    //       y: '37.2292667',
    //       stationSeq: 83,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29432',
    //       regionName: '용인',
    //       stationId: '228000196',
    //       stationName: '남동구미마을',
    //       x: '127.2090833',
    //       y: '37.2272333',
    //       stationSeq: 84,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29424',
    //       regionName: '용인',
    //       stationId: '228000195',
    //       stationName: '보보스타운',
    //       x: '127.2039667',
    //       y: '37.2270667',
    //       stationSeq: 85,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29414',
    //       regionName: '용인',
    //       stationId: '228000194',
    //       stationName: '교수마을',
    //       x: '127.1981167',
    //       y: '37.2260167',
    //       stationSeq: 86,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29851',
    //       regionName: '용인',
    //       stationId: '228000193',
    //       stationName: '동진마을',
    //       x: '127.1934333',
    //       y: '37.2265333',
    //       stationSeq: 87,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 47946',
    //       regionName: '용인',
    //       stationId: '228002959',
    //       stationName: '명지대앞',
    //       x: '127.1885833',
    //       y: '37.22585',
    //       stationSeq: 88,
    //       turnYn: 'N',
    //     },
    //     {
    //       centerYn: 'N',
    //       districtCd: '2',
    //       mobileNo: ' 29403',
    //       regionName: '용인',
    //       stationId: '228000192',
    //       stationName: '명지대',
    //       x: '127.1883667',
    //       y: '37.2241833',
    //       stationSeq: 89,
    //       turnYn: 'N',
    //     },
    //   ],
    // } as unknown as RouteMapInfo;
    const END_POINT = `http://localhost:3000/routeMap`;
    const URL = `${END_POINT}/${routeId}`;

    const res = await fetch(URL);
    return res.json() as unknown as RouteMapInfo;
  } catch {
    throw new Error('RouteMap fetch error');
  }
};

export const useRouteMap = (routeId: string) => {
  const queryClient = useQueryClient();

  const query = useQuery<RouteMapInfo>({
    queryKey: ['routeMap', routeId],
    queryFn: async () => fetchRouteMap(routeId),
  });

  const mutation = useMutation({
    mutationFn: fetchRouteMap,
    onSuccess: () =>
      queryClient.invalidateQueries({
        queryKey: ['routeMap'],
      }),
  });

  return { ...query, mutation };
};
